COMP: DTIProcess was not compiling
niral_utilities/PolydataMerge/polydatamerge.cpp:19:10: fatal error:
      'vtkPolyDataReader.h' file not found

Need to specify components when nested includes of VTK are used
with newer versions of cmake.

~/src/NEP-11/VTK/Utilities/Maintenance/WhatModulesVTK.py ~/src/NEP-11/VTK \
           ~/src/NEP-11/DTIProcess-build/niral_utilities-build/CurveCompare